create user C##myboard
IDENTIFIED BY myboard
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE TO C##myboard;
GRANT CREATE SEQUENCE TO C##myboard;
ALTER USER C##myboard QUOTA UNLIMITED ON USERS;